# Generated by Django 5.1 on 2024-08-16 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('nameEng', models.CharField(max_length=50)),
                ('birthCertNo', models.CharField(blank=True, max_length=30, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(blank=True, max_length=20, null=True)),
                ('fatherName', models.CharField(max_length=50)),
                ('fatherNameEng', models.CharField(max_length=50)),
                ('fatherNID', models.CharField(blank=True, max_length=30, null=True)),
                ('fatherDob', models.DateField(blank=True, null=True)),
                ('fatherMobile', models.CharField(blank=True, max_length=15, null=True)),
                ('motherName', models.CharField(max_length=50)),
                ('motherNameEng', models.CharField(max_length=50)),
                ('motherNID', models.CharField(blank=True, max_length=30, null=True)),
                ('motherDob', models.DateField(blank=True, null=True)),
                ('motherMobile', models.CharField(blank=True, max_length=15, null=True)),
                ('presentDiv', models.CharField(blank=True, max_length=50, null=True)),
                ('presentDist', models.CharField(blank=True, max_length=50, null=True)),
                ('presentUpozila', models.CharField(blank=True, max_length=50, null=True)),
                ('presentUnion', models.CharField(blank=True, max_length=50, null=True)),
                ('presentPost', models.CharField(blank=True, max_length=50, null=True)),
                ('presentVill', models.CharField(blank=True, max_length=50, null=True)),
                ('permanentDiv', models.CharField(blank=True, max_length=50, null=True)),
                ('permanentDist', models.CharField(blank=True, max_length=50, null=True)),
                ('permanentUpozila', models.CharField(blank=True, max_length=50, null=True)),
                ('permanentUnion', models.CharField(blank=True, max_length=50, null=True)),
                ('permanentPost', models.CharField(blank=True, max_length=50, null=True)),
                ('permanentVill', models.CharField(blank=True, max_length=50, null=True)),
                ('prevEduDivi', models.CharField(blank=True, max_length=50, null=True)),
                ('prevEduDist', models.CharField(blank=True, max_length=50, null=True)),
                ('prevEduUpozila', models.CharField(blank=True, max_length=50, null=True)),
                ('prevEduInst', models.CharField(blank=True, max_length=50, null=True)),
                ('prevEduBoard', models.CharField(blank=True, max_length=50, null=True)),
                ('prevEduPassYear', models.CharField(blank=True, max_length=50, null=True)),
                ('prevEduTech', models.CharField(blank=True, max_length=50, null=True)),
                ('prevEduExam', models.CharField(blank=True, max_length=50, null=True)),
                ('prevEduRoll', models.CharField(blank=True, max_length=50, null=True)),
                ('prevEduReg', models.CharField(blank=True, max_length=50, null=True)),
                ('prevEduResult', models.CharField(blank=True, max_length=50, null=True)),
                ('presentEduDivi', models.CharField(blank=True, max_length=50, null=True)),
                ('presentEduDist', models.CharField(blank=True, max_length=50, null=True)),
                ('presentEduUpozila', models.CharField(blank=True, max_length=50, null=True)),
                ('presentEduInstitute', models.CharField(blank=True, max_length=50, null=True)),
                ('presentEduSem', models.CharField(blank=True, max_length=20, null=True)),
                ('presentEduTech', models.CharField(blank=True, max_length=50, null=True)),
                ('presentEduShift', models.CharField(blank=True, max_length=15, null=True)),
                ('presentEduRoll', models.CharField(blank=True, max_length=10, null=True)),
                ('guardian', models.CharField(blank=True, max_length=15, null=True)),
                ('guardianName', models.CharField(blank=True, max_length=50, null=True)),
                ('guardianNameEng', models.CharField(blank=True, max_length=50, null=True)),
                ('guardianNID', models.CharField(blank=True, max_length=30, null=True)),
                ('guardianDob', models.DateField(blank=True, null=True)),
                ('guardianMobile', models.CharField(blank=True, max_length=15, null=True)),
                ('eduCostBearer', models.CharField(blank=True, max_length=15, null=True)),
                ('freedomFighter', models.CharField(blank=True, max_length=5, null=True)),
                ('protibondhi', models.CharField(blank=True, max_length=5, null=True)),
                ('nrigosti', models.CharField(blank=True, max_length=5, null=True)),
                ('otherScholar', models.CharField(blank=True, max_length=5, null=True)),
                ('applicantPhoto', models.ImageField(blank=True, null=True, upload_to='stdImg')),
                ('documents', models.ImageField(blank=True, null=True, upload_to='extraFile')),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentAccountName', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentAccountNID', models.CharField(blank=True, max_length=25, null=True)),
                ('paymentType', models.CharField(blank=True, max_length=20, null=True)),
                ('paymentAccountNo', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentMobileBankName', models.CharField(blank=True, max_length=15, null=True)),
                ('paymentBankName', models.CharField(blank=True, max_length=50, null=True)),
                ('paymentBankBranch', models.CharField(blank=True, max_length=50, null=True)),
                ('bankAccountType', models.CharField(blank=True, max_length=50, null=True)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentPayment', to='home.studentsaf')),
            ],
        ),
        migrations.AddField(
            model_name='studentsaf',
            name='presentEduSession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.year'),
        ),
    ]
