# Generated by Django 4.2.17 on 2024-12-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_studentsaf_presentedusession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
