# Generated by Django 5.1 on 2024-12-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_allstudent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllStudent',
        ),
    ]
